[project]
name = "rock-paper-scissor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "streamlit>=1.44.1",
]
